services:
  homeassistant:
    container_name: homeassistant-dotfiles
    image: ghcr.io/hassio-addons/ssh/amd64:stable
    platform: linux/amd64
    volumes: [./:/home/testuser/dotfiles]
    stop_grace_period: 0s
    working_dir: /home/testuser/dotfiles
    entrypoint: /bin/bash -c
    environment:
      PATH: /home/testuser/.cargo/bin:/home/testuser/.local/bin:$PATH
      OS: linux
      HOME: /home/testuser
    restart: no

  macos:
    container_name: macos-dotfiles
    image: sickcodes/docker-osx:latest
    platform: linux/amd64
    working_dir: /app
    volumes: [./:/app]
    command: /bin/bash -c /app/install
    environment:
      OS: macos
      PATH: /home/linuxbrew/.linuxbrew/bin:$PATH
    stop_grace_period: 0s
    restart: no
    
  codespaces:
    container_name: codespaces-dotfiles
    image: mcr.microsoft.com/devcontainers/base:0-jammy
    platform: linux/amd64
    volumes: [./:/home/codespace/dotfiles]
    working_dir: /home/codespace/dotfiles
    environment:
      CODESPACES: "true"
      GITHUB_USER: oleander
      HOME: /home/codespace
      USER: codespace
      PATH: /home/codespace/.local/bin:/home/codespace/.cargo/bin:$PATH
    stop_grace_period: 0s
    restart: no
    entrypoint: /bin/bash -c
