services:
  homeassistant:
    container_name: homeassistant-dotfiles
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes: [./:/root/dotfiles]
    working_dir: /root/dotfiles
    command: ["./test/test_ssh_keys.sh"]
    environment:
      PATH: /root/.cargo/bin:$PATH
      OS: linux
    user: root
    restart: no

  macos:
    container_name: macos-dotfiles
    image: sickcodes/docker-osx:latest
    platform: linux/amd64
    volumes: [./:/app]
    entrypoint: /bin/bash -c /app/install
    environment:
      OS: macos
      PATH: /home/linuxbrew/.linuxbrew/bin:$PATH
    stop_grace_period: 0s
    restart: no
