services:
  homeassistant:
    container_name: homeassistant-dotfiles
    image: ghcr.io/hassio-addons/ssh/amd64:stable
    platform: linux/amd64
    volumes: [./:/root/dotfiles]
    entrypoint: /root/dotfiles/install
    stop_grace_period: 0s
    environment:
      PATH: /root/.cargo/bin:$PATH
      OS: linux
    user: root
    restart: no

  macos:
    container_name: macos-dotfiles
    image: sickcodes/docker-osx:latest
    platform: linux/amd64
    volumes: [./:/app]
    entrypoint: /bin/bash -c /app/install
    environment:
      OS: macos
      PATH: /home/linuxbrew/.linuxbrew/bin:$PATH
    stop_grace_period: 0s
    restart: no
