version: '3'

services:
  codespaces:
    container_name: codespaces-test
    image: mcr.microsoft.com/vscode/devcontainers/universal:latest
    platform: linux/amd64
    volumes:
      - ./:/home/codespace/dotfiles
    working_dir: /home/codespace/dotfiles
    environment:
      - CODESPACES=true
      - GITHUB_USER=oleander
      - HOME=/home/codespace
      - USER=codespace
    command: /bin/bash -c "cd /home/codespace/dotfiles && ./test/verify-codespaces.sh"
    tty: true
    stdin_open: true