services:
  homeassistant:
    container_name: homeassistant-dotfiles
    build:
      context: .
      dockerfile: test/Dockerfile
    platform: linux/amd64
    volumes: [./:/home/testuser/dotfiles]
    stop_grace_period: 0s
    working_dir: /home/testuser/dotfiles
    environment:
      PATH: /home/testuser/.cargo/bin:$PATH
      OS: linux
    restart: no

  macos:
    container_name: macos-dotfiles
    image: sickcodes/docker-osx:latest
    platform: linux/amd64
    working_dir: /app
    volumes: [./:/app]
    command: /bin/bash -c /app/install
    environment:
      OS: macos
      PATH: /home/linuxbrew/.linuxbrew/bin:$PATH
    stop_grace_period: 0s
    restart: no
