#!/usr/bin/env ruby -w

begin
  require "hirb"
  Hirb.enable
rescue LoadError
  puts "The hirb gem isn't installed."
  puts "Run 'gem install cldwalker-hirb' to install it"
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end