#!/usr/bin/env bash

set -e

if command -v brew &>/dev/null; then
  echo "Homebrew already installed"
  exit 0
fi

echo "Installing home brew"
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
