#!/usr/bin/env bash

set -e

if ! command -v brew &>/dev/null; then
    echo "brew is not installed"
    exit 1
fi

if ! command -v cargo &>/dev/null; then
    echo "Installing rust with cargo"
    curl https://sh.rustup.rs -sSf | sh
fi

if ! command -v cargo-binstall &>/dev/null; then
    echo "cargo-binstall is not installed"
    exit 1
fi

echo "Installing git-ai using cargo-binstall"
cargo binstall -y --force git-ai
