#!/usr/bin/env bash

set -e

test -n "$QUICK" && exit 0

if command -v cargo &>/dev/null; then
    echo "rust/cargo is already installed"
    exit 0
fi

if ! command -v brew &>/dev/null; then
    echo "brew is not installed"
    exit 1
fi

brew install rustup
