#!/usr/bin/env bash

set -e

if command -v zsh &>/dev/null; then
    echo "zsh is already installed"
    exit 0
fi

export NONINTERACTIVE=1

if ! command -v brew &>/dev/null; then
    echo "Installing homebrew"
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
fi

echo "Installing zsh"
brew install zsh
