#!/usr/bin/env bash

set -e

if command -v zsh &>/dev/null; then
    echo "zsh is already installed"
    exit 0
fi

if ! command -v brew &>/dev/null; then
    echo "brew is not installed"
    exit 1
fi

echo "Installing zsh"
brew install zsh
