---
defaultTest:
  options:
    provider: openai:gpt-4o

prompts: [system.md]

providers:
  - config:
      temperature: 0.1
    id: openai:gpt-4o
    label: gpt-4

  - config:
      max_tokens: 72
      temperature: 0.7
    id: openai:gpt-4o
    label: gpt-4

tests:
  - vars: tests.yml
  - assert:
      - type: factuality
        value: {{docs}}
      - type: llm-rubric
        value: The examples in the output is as compressed as possible
