---
defaultTest:
  options:
    provider: openai:gpt-4o

prompts: [system.md]

providers:
  - config:
      temperature: 0.7
    id: openai:gpt-4o
    label: gpt-4o-temp:0.7
  - config:
      temperature: 0.3
    id: openai:gpt-4o
    label: gpt-4o-temp:0.3

  - config:
      temperature: 0.5
    id: openai:gpt-4o
    label: gpt-4o-temp:0.5

tests:
  - vars: tests.yml
  - assert:
      - type: llm-rubric
        value: |
          Each example includes
          - a description (Desc:)
          - the necessary Cargo feature (Feature:) (if any)
          - and a use case (Usage:)
      - type: llm-rubric
        value: Each example contains minimal duplication, i.e `#[derive(StructOpt)]`
      - type: factuality
        value: The required Cargo features for each code snippet are correctly specified in {{summary}}
      - type: llm-rubric
        value: Comments are provided to explain the use cases of the code snippets
      - type: select-best
        value: |
          Select the one where the OUTPUT matches the INPUT in the most meaningful way
          OUTPUT: {{summary}}
          INPUT: {{docs}}
