eval "$(rbenv init -)"

export ROOT=$HOME/.dotfiles

. $ROOT/zsh/config
. $ROOT/zsh/paths
. $ROOT/zsh/aliases/base
. $ROOT/zsh/aliases/git
. $ROOT/zsh/aliases/ruby
. $ROOT/zsh/completion


# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
# [ -f ~/.rvm/scripts/rvm ] && . ~/.rvm/scripts/rvm

# added by travis gem
# [ -f /Users/oleander/.travis/travis.sh ] && source /Users/oleander/.travis/travis.sh
# [ -f ~/.bundler-exec.sh ] && source ~/.bundler-exec.sh

# added by travis gem
[ ! -s ~/.travis/travis.sh ] || source ~/.travis/travis.sh
