#!/bin/bash -e

if ! command -v cargo &>/dev/null; then
    echo "cargo is not installed"
    exit 1
fi

sudo apk add --no-cache make

if ! command -v cargo-binstall &>/dev/null; then
    echo "cargo-binstall is not installed"
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
fi

# Install git-ai
cargo binstall -y git-ai
