#!/usr/bin/env bash

set -e
set -x

BRANCH=$(git rev-parse --abbrev-ref HEAD)

git commit --no-edit -a || true
git push origin "$BRANCH"

HOST=$1
if [ -z "$HOST" ]; then
  echo "Usage: $0 <host>"
  exit 1
fi

ssh "$HOST" <<EOF
  cd ~/.dotfiles
  git stash --include-untracked
  git pull origin "$BRANCH"
  git checkout "$BRANCH"
  ./install
EOF
