#!/usr/bin/env bash

set -e
set -x

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

git commit --no-edit -a || true
git push origin "$CURRENT_BRANCH"

ssh homeassistant ./deploy "$CURRENT_BRANCH"
ssh homeassistant ./verify
