#!/usr/bin/env bash

set -e

if [[ -d ~/.autojump ]]; then
    echo "autojump already installed"
    exit 0
fi

export SHELL=/bin/bash

rm -rf autojump
git clone https://github.com/wting/autojump.git
cd autojump
./install.py
echo "source $HOME/.autojump/etc/profile.d/autojump.sh" >> ~/.zshrc

