#!/usr/bin/env bash

set -e

export SHELL=/bin/bash

rm -rf autojump
git clone https://github.com/wting/autojump.git
cd autojump
./install.py
echo "source /root/.autojump/etc/profile.d/autojump.sh" >> ~/.zshrc

