# # https://github.com/sds/overcommit/blob/master/config/default.yml
quiet: true
concurrency: 6
verify_signatures: false

PreCommit:
  ALL:
    quiet: true
    problem_on_unmodified_line: ignore
  ForbiddenBranches:
    enabled: true
    branches: [master]
  FileSize:
    enabled: true
  FixMe:
    enabled: true
  HardTabs:
    enabled: true
PrePush:
  ProtectedBranches:
    enabled: true
    branches: [master]
CommitMsg:
  HardTabs:
    enabled: true
PreRebase:
  MergedCommits:
    enabled: true
    branches: [master]
PrepareCommitMsg:
  ALL:
    quiet: true
  ReplaceBranch:
    enabled: true
    branch_pattern: '(KDB-\d+)[^\d]*'
    replacement_text: '\1 '
    skipped_commit_types: ['merge', 'squash']
    skip_if_pattern_matches_commit_message: true
    skip_if: ['test', '!', '-d', '.git/refs/remotes/origin/demo']
    on_warn: pass
    on_fail: pass
