# https://github.com/sds/overcommit/blob/master/config/default.yml
quiet: false
concurrency: 6
verify_signatures: false

PreCommit:
  ALL:
    problem_on_unmodified_line: ignore
  RFix:
    enabled: true
    command: rfix
    flags: ['local', '--dry']
    description: "Lint changes since last push using RuboCop"
    install_command: ["gem", "install", "rfix"]
    parallelize: true
    required_executable: rfix
    problem_on_unmodified_line: report
  CodeSpellCheck:
    enabled: true
  Fasterer:
    enabled: true
  FileSize:
    enabled: true
  FixMe:
    enabled: true
  TravisLint:
    enabled: true
    flags: ['lint', '-x']
CommitMsg:
  HardTabs:
    enabled: true
  SpellCheck:
    enabled: true
