version = "Two"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = false
short_array_element_width_threshold = 50
single_line_let_else_max_width = 0

match_block_trailing_comma = true
enum_discrim_align_threshold = 40
struct_field_align_threshold = 40
fn_params_layout = "Compressed"
use_field_init_shorthand = true
struct_lit_single_line = false
imports_granularity = "Module"
imports_layout = "Horizontal"
force_multiline_blocks = true
use_small_heuristics = "Max"
normalize_comments = false
imports_indent = "Block"
where_single_line = true
trailing_comma = "Never"
reorder_modules = false
newline_style = "Auto"
group_imports = "Preserve"
hard_tabs = false
max_width = 130
chain_width = 90
tab_spaces = 2


fn_call_width = 100
