short_array_element_width_threshold = 50
single_line_let_else_max_width = 0
group_imports = "StdExternalCrate"
enum_discrim_align_threshold = 40
struct_field_align_threshold = 40
fn_params_layout = "Compressed"
use_field_init_shorthand = true
overflow_delimited_expr = true
struct_lit_single_line = true
imports_granularity = "Module"
imports_layout = "Horizontal"
force_multiline_blocks = true
use_small_heuristics = "Max"
normalize_comments = false
reorder_impl_items = true
imports_indent = "Block"
trailing_comma = "Never"
reorder_imports = false
reorder_modules = false
newline_style = "Auto"
fn_call_width = 90
hard_tabs = false
version = "Two"
max_width = 140
tab_spaces = 2

attr_fn_like_width = 120
match_block_trailing_comma = false
where_single_line = false
chain_width = 60
edition = "2021"
struct_variant_width = 0
single_line_if_else_max_width = 0

match_arm_blocks = false
struct_lit_width = 50
