eval "$(rbenv init --no-rehash - zsh)"
eval "$(starship init zsh)"
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/linus/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
