name: Verify Dotfiles Setup

on:
  push:
    branches:
      - main
      - fix/codespace
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build devcontainer
        run: devcontainer build --workspace-folder .

      - name: Run devcontainer
        run: devcontainer up --workspace-folder .

      - name: Verify dotfiles setup
        run: devcontainer exec --workspace-folder . ls
