name: Verify Dotfiles Setup

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Docker compose test for linux
        run: docker compose up homeassistant --build

      - name: Docker compose test for macos
        run: docker compose up macos --build
