name: Verify Dotfiles Setup

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Docker compose test for linux
        run: docker compose up homeassistant --build

      - name: Docker compose test for macos
        run: docker compose up macos --build

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build devcontainer
        run: devcontainer build --workspace-folder .

      - name: Run devcontainer
        run: devcontainer up --remote-env OS=linux --workspace-folder .

      # Modified to run installation and verification in a single bash session
      - name: Install and verify dotfiles
        run: |
          devcontainer exec --remote-env OS=linux --workspace-folder . /bin/bash -c '
          # Run dotfiles installation
          ./install && \
          # Run Rust installer explicitly and wait for cargo env to be available
          ~/.local/bin/inst-rust && \
          while [ ! -f ~/.cargo/env ]; do sleep 1; done && \
          source ~/.cargo/env && \
          # Update rust to 1.69 minimum version required by ctrlc dependency
          rustup toolchain install 1.69 && \
          rustup default 1.69 && \
          # Try installing git-ai with retries
          for i in {1..3}; do
            echo "Attempt $i to install git-ai..." && \
            timeout 60s ~/.local/bin/inst-git-ai && break || \
            echo "Installation attempt $i failed, cleaning up..." && \
            rm -rf ~/.cargo/.package-cache && \
            sleep 5
          done && \
          # Verify installation
          echo "Verifying installation..." && \
          ls -la ~/.local/bin && \
          which git-ai && \
          cargo --version
          '
