name: Verify Dotfiles Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker

      - name: Run docker container
        run: |
          docker build -t dotfiles .
          docker run -ti dotfiles ls
