name: Verify Dotfiles Setup

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dip
        run: gem install dip

      - name: Docker compose test for linux
        run: dip test-linux

      - name: Test install in linux
        run: dip install-linux
