name: Test GitHub Codespaces Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-with-dip:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dip
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install dip
      
      - name: Make scripts executable
        run: |
          chmod +x ./install
          chmod +x ./inst/github/*
      
      - name: Run setup in Codespaces container
        run: dip install-codespaces
      
      - name: Verify installation in Codespaces container
        run: dip verify-codespaces

  # Additional test directly in GitHub Actions container
  test-in-container:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:0-jammy
    env:
      CODESPACES: true
      GITHUB_USER: oleander
    
    steps:
      - uses: actions/checkout@v3
        with:
          path: ~/.dotfiles
      
      - name: Make scripts executable
        run: |
          cd ~/.dotfiles
          chmod +x ./install
          chmod +x ./inst/github/*
      
      - name: Run setup
        run: |
          cd ~/.dotfiles
          ./inst/github/setup
      
      - name: Verify installation
        run: |
          cd ~/.dotfiles
          ./inst/github/test